security:
  oauth2:
    client:
      clientId: 141512451225764
      clientSecret: ab816f8155909daf6bb7e752a77dab95
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me